### ISSUE TITLE
Unable to start Griffon RC4

### ISSUE THREAD

**Issue by BlackHatJohnDoe** [gtkcyber/griffon-vm#1]
After following the `installation.md` instructions, I was presented with the following error:
```
Implementation of the USB 2.0 controller not found!
Because the USB 2.0 controller state is part of the saved VM state, the VM cannot be started. To fix this problem, either install the 'Oracle VM VirtualBox Extension Pack' or disable USB 2.0 support in the VM settings.
Note! This error could also mean that an incompatible version of the 'Oracle VM VirtualBox Extension Pack' is installed (VERR_NOT_FOUND).

Result Code: | NS_ERROR_FAILURE (0x80004005)
...
```

After installing the extension pack, things worked perfectly fine.  Unless USB 2.0 support is necessary, perhaps you could disable it before creating the .ova and just re-upload to Google Drive (and update [the hashes](https://github.com/gtkcyber/griffon-vm#downloading-griffon)).

Side note: If you choose to update the `instructions.md` instead of asking that people install the extensions, brew had a cask for this that worked fine (relevant to macOS systems - `brew cask install virtualbox-extension-pack`), but there are [other ways to install](https://www.virtualbox.org/wiki/Downloads) (There are some details in the [User Manual](https://www.virtualbox.org/manual/ch01.html#intro-installing)) that you may want to point people to.

**Comment by austin-taylor** [comment]
Thank you @BlackHatJohnDoe Will update VM and repost.

**Comment by mryap** [comment]
I want to download and check it out but was deterred by the big file size which is a staggering 8GB. Is there a basic collections of tools to start with? like those at https://winpython.github.io/  Thanks

**Comment by cgivre** [comment]
@mryap It is a large file, however Griffon is meant to be a lot more than WinPython or Anaconda.  Griffon has a whole collection of big data tools, databases, visualization tools and more.  If you want just Python, I'd recommend Anaconda by Continuum Analytics.
